name: Update USDJPY Outlook

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    # You can also set env here at the job level:
    # env:
    #   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Fetch USDJPY direction
        # inject the secret into this step:
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 fetch_usdjpy.py

      - name: Commit & push usdjpy.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add usdjpy.json
          git diff --quiet || git commit -m "Daily update of USDJPY direction"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
