permissions:
  contents: write   # grant write access so the action can commit & push

name: Update USDJPY Outlook

on:
  schedule:
    # Every day at 08:00 Europe/Ljubljana (UTC+2) → 06:00 UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai yfinance pandas_ta

      - name: Fetch USDJPY direction
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 fetch_usdjpy.py

      - name: Commit & push usdjpy.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add usdjpy.json
          git diff --quiet || git commit -m "Daily update of USDJPY direction"
          git push
