name: Update USDJPY Outlook

on:
  schedule:
    # Every day at 08:00 Europe/Ljubljana (UTC+2) → 06:00 UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write  # Allow committing back to the repo

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # allow pushing with GITHUB_TOKEN

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Fetch USDJPY direction
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python3 fetch_usdjpy.py

      - name: Debug JSON
        run: cat usdjpy.json

      - name: Commit JSON
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Daily update of USDJPY outlook"
          add: "usdjpy.json"
